
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CardPhoto': typeof import("../components/card/photo.vue")['default']
    'CardRegion': typeof import("../components/card/region.vue")['default']
    'ElementsButton': typeof import("../components/elements/button.vue")['default']
    'ElementsInput': typeof import("../components/elements/input.vue")['default']
    'ElementsSearch': typeof import("../components/elements/search.vue")['default']
    'ElementsSort': typeof import("../components/elements/sort.vue")['default']
    'ElementsTag': typeof import("../components/elements/tag.vue")['default']
    'ElementsTextarea': typeof import("../components/elements/textarea.vue")['default']
    'Footer': typeof import("../components/footer/footer.vue")['default']
    'Header': typeof import("../components/header/header.vue")['default']
    'HeaderLk': typeof import("../components/header/lk.vue")['default']
    'MainBanner': typeof import("../components/main/banner.vue")['default']
    'MainTag': typeof import("../components/main/tag.vue")['default']
    'MainTagSlider': typeof import("../components/main/tagSlider.vue")['default']
    'PhotoDetailInfo': typeof import("../components/photoDetail/info.vue")['default']
    'PhotoDetailMap': typeof import("../components/photoDetail/map.vue")['default']
    'PhotoDetailSlider': typeof import("../components/photoDetail/slider.vue")['default']
    'UserAwards': typeof import("../components/user/awards.vue")['default']
    'UserMainInfo': typeof import("../components/user/mainInfo.vue")['default']
    'UserPhotos': typeof import("../components/user/photos.vue")['default']
    'UserPopup': typeof import("../components/user/popup/index.vue")['default']
    'UserPopupText': typeof import("../components/user/popup/text.vue")['default']
    'UserPopupUpload': typeof import("../components/user/popup/upload.vue")['default']
    'UserPopupSecond': typeof import("../components/user/popupSecond.vue")['default']
    'IconArrowLine': typeof import("../assets/icons/arrow-line")['default']
    'IconArrow': typeof import("../assets/icons/arrow")['default']
    'IconAward': typeof import("../assets/icons/award")['default']
    'IconBackArrow': typeof import("../assets/icons/back-arrow")['default']
    'IconBannerArrow': typeof import("../assets/icons/banner-arrow")['default']
    'IconBchp': typeof import("../assets/icons/bchp")['default']
    'IconBearOff': typeof import("../assets/icons/bear-off")['default']
    'IconBearOn': typeof import("../assets/icons/bear-on")['default']
    'IconBusOff': typeof import("../assets/icons/bus-off")['default']
    'IconBusOn': typeof import("../assets/icons/bus-on")['default']
    'IconBus': typeof import("../assets/icons/bus")['default']
    'IconCheckbox': typeof import("../assets/icons/checkbox")['default']
    'IconEye': typeof import("../assets/icons/eye")['default']
    'IconLikeDef': typeof import("../assets/icons/like-def")['default']
    'IconLike': typeof import("../assets/icons/like")['default']
    'IconLogoWhite': typeof import("../assets/icons/logo-white")['default']
    'IconLogo': typeof import("../assets/icons/logo")['default']
    'IconMap': typeof import("../assets/icons/map")['default']
    'IconPlusWhite': typeof import("../assets/icons/plus-white")['default']
    'IconPlus': typeof import("../assets/icons/plus")['default']
    'IconSearch': typeof import("../assets/icons/search")['default']
    'IconStar': typeof import("../assets/icons/star")['default']
    'IconTreeOff': typeof import("../assets/icons/tree-off")['default']
    'IconTreeOn': typeof import("../assets/icons/tree-on")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtIcon': typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCardPhoto': typeof import("../components/card/photo.vue")['default']
    'LazyCardRegion': typeof import("../components/card/region.vue")['default']
    'LazyElementsButton': typeof import("../components/elements/button.vue")['default']
    'LazyElementsInput': typeof import("../components/elements/input.vue")['default']
    'LazyElementsSearch': typeof import("../components/elements/search.vue")['default']
    'LazyElementsSort': typeof import("../components/elements/sort.vue")['default']
    'LazyElementsTag': typeof import("../components/elements/tag.vue")['default']
    'LazyElementsTextarea': typeof import("../components/elements/textarea.vue")['default']
    'LazyFooter': typeof import("../components/footer/footer.vue")['default']
    'LazyHeader': typeof import("../components/header/header.vue")['default']
    'LazyHeaderLk': typeof import("../components/header/lk.vue")['default']
    'LazyMainBanner': typeof import("../components/main/banner.vue")['default']
    'LazyMainTag': typeof import("../components/main/tag.vue")['default']
    'LazyMainTagSlider': typeof import("../components/main/tagSlider.vue")['default']
    'LazyPhotoDetailInfo': typeof import("../components/photoDetail/info.vue")['default']
    'LazyPhotoDetailMap': typeof import("../components/photoDetail/map.vue")['default']
    'LazyPhotoDetailSlider': typeof import("../components/photoDetail/slider.vue")['default']
    'LazyUserAwards': typeof import("../components/user/awards.vue")['default']
    'LazyUserMainInfo': typeof import("../components/user/mainInfo.vue")['default']
    'LazyUserPhotos': typeof import("../components/user/photos.vue")['default']
    'LazyUserPopup': typeof import("../components/user/popup/index.vue")['default']
    'LazyUserPopupText': typeof import("../components/user/popup/text.vue")['default']
    'LazyUserPopupUpload': typeof import("../components/user/popup/upload.vue")['default']
    'LazyUserPopupSecond': typeof import("../components/user/popupSecond.vue")['default']
    'LazyIconArrowLine': typeof import("../assets/icons/arrow-line")['default']
    'LazyIconArrow': typeof import("../assets/icons/arrow")['default']
    'LazyIconAward': typeof import("../assets/icons/award")['default']
    'LazyIconBackArrow': typeof import("../assets/icons/back-arrow")['default']
    'LazyIconBannerArrow': typeof import("../assets/icons/banner-arrow")['default']
    'LazyIconBchp': typeof import("../assets/icons/bchp")['default']
    'LazyIconBearOff': typeof import("../assets/icons/bear-off")['default']
    'LazyIconBearOn': typeof import("../assets/icons/bear-on")['default']
    'LazyIconBusOff': typeof import("../assets/icons/bus-off")['default']
    'LazyIconBusOn': typeof import("../assets/icons/bus-on")['default']
    'LazyIconBus': typeof import("../assets/icons/bus")['default']
    'LazyIconCheckbox': typeof import("../assets/icons/checkbox")['default']
    'LazyIconEye': typeof import("../assets/icons/eye")['default']
    'LazyIconLikeDef': typeof import("../assets/icons/like-def")['default']
    'LazyIconLike': typeof import("../assets/icons/like")['default']
    'LazyIconLogoWhite': typeof import("../assets/icons/logo-white")['default']
    'LazyIconLogo': typeof import("../assets/icons/logo")['default']
    'LazyIconMap': typeof import("../assets/icons/map")['default']
    'LazyIconPlusWhite': typeof import("../assets/icons/plus-white")['default']
    'LazyIconPlus': typeof import("../assets/icons/plus")['default']
    'LazyIconSearch': typeof import("../assets/icons/search")['default']
    'LazyIconStar': typeof import("../assets/icons/star")['default']
    'LazyIconTreeOff': typeof import("../assets/icons/tree-off")['default']
    'LazyIconTreeOn': typeof import("../assets/icons/tree-on")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtIcon': typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CardPhoto: typeof import("../components/card/photo.vue")['default']
export const CardRegion: typeof import("../components/card/region.vue")['default']
export const ElementsButton: typeof import("../components/elements/button.vue")['default']
export const ElementsInput: typeof import("../components/elements/input.vue")['default']
export const ElementsSearch: typeof import("../components/elements/search.vue")['default']
export const ElementsSort: typeof import("../components/elements/sort.vue")['default']
export const ElementsTag: typeof import("../components/elements/tag.vue")['default']
export const ElementsTextarea: typeof import("../components/elements/textarea.vue")['default']
export const Footer: typeof import("../components/footer/footer.vue")['default']
export const Header: typeof import("../components/header/header.vue")['default']
export const HeaderLk: typeof import("../components/header/lk.vue")['default']
export const MainBanner: typeof import("../components/main/banner.vue")['default']
export const MainTag: typeof import("../components/main/tag.vue")['default']
export const MainTagSlider: typeof import("../components/main/tagSlider.vue")['default']
export const PhotoDetailInfo: typeof import("../components/photoDetail/info.vue")['default']
export const PhotoDetailMap: typeof import("../components/photoDetail/map.vue")['default']
export const PhotoDetailSlider: typeof import("../components/photoDetail/slider.vue")['default']
export const UserAwards: typeof import("../components/user/awards.vue")['default']
export const UserMainInfo: typeof import("../components/user/mainInfo.vue")['default']
export const UserPhotos: typeof import("../components/user/photos.vue")['default']
export const UserPopup: typeof import("../components/user/popup/index.vue")['default']
export const UserPopupText: typeof import("../components/user/popup/text.vue")['default']
export const UserPopupUpload: typeof import("../components/user/popup/upload.vue")['default']
export const UserPopupSecond: typeof import("../components/user/popupSecond.vue")['default']
export const IconArrowLine: typeof import("../assets/icons/arrow-line")['default']
export const IconArrow: typeof import("../assets/icons/arrow")['default']
export const IconAward: typeof import("../assets/icons/award")['default']
export const IconBackArrow: typeof import("../assets/icons/back-arrow")['default']
export const IconBannerArrow: typeof import("../assets/icons/banner-arrow")['default']
export const IconBchp: typeof import("../assets/icons/bchp")['default']
export const IconBearOff: typeof import("../assets/icons/bear-off")['default']
export const IconBearOn: typeof import("../assets/icons/bear-on")['default']
export const IconBusOff: typeof import("../assets/icons/bus-off")['default']
export const IconBusOn: typeof import("../assets/icons/bus-on")['default']
export const IconBus: typeof import("../assets/icons/bus")['default']
export const IconCheckbox: typeof import("../assets/icons/checkbox")['default']
export const IconEye: typeof import("../assets/icons/eye")['default']
export const IconLikeDef: typeof import("../assets/icons/like-def")['default']
export const IconLike: typeof import("../assets/icons/like")['default']
export const IconLogoWhite: typeof import("../assets/icons/logo-white")['default']
export const IconLogo: typeof import("../assets/icons/logo")['default']
export const IconMap: typeof import("../assets/icons/map")['default']
export const IconPlusWhite: typeof import("../assets/icons/plus-white")['default']
export const IconPlus: typeof import("../assets/icons/plus")['default']
export const IconSearch: typeof import("../assets/icons/search")['default']
export const IconStar: typeof import("../assets/icons/star")['default']
export const IconTreeOff: typeof import("../assets/icons/tree-off")['default']
export const IconTreeOn: typeof import("../assets/icons/tree-on")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtIcon: typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCardPhoto: typeof import("../components/card/photo.vue")['default']
export const LazyCardRegion: typeof import("../components/card/region.vue")['default']
export const LazyElementsButton: typeof import("../components/elements/button.vue")['default']
export const LazyElementsInput: typeof import("../components/elements/input.vue")['default']
export const LazyElementsSearch: typeof import("../components/elements/search.vue")['default']
export const LazyElementsSort: typeof import("../components/elements/sort.vue")['default']
export const LazyElementsTag: typeof import("../components/elements/tag.vue")['default']
export const LazyElementsTextarea: typeof import("../components/elements/textarea.vue")['default']
export const LazyFooter: typeof import("../components/footer/footer.vue")['default']
export const LazyHeader: typeof import("../components/header/header.vue")['default']
export const LazyHeaderLk: typeof import("../components/header/lk.vue")['default']
export const LazyMainBanner: typeof import("../components/main/banner.vue")['default']
export const LazyMainTag: typeof import("../components/main/tag.vue")['default']
export const LazyMainTagSlider: typeof import("../components/main/tagSlider.vue")['default']
export const LazyPhotoDetailInfo: typeof import("../components/photoDetail/info.vue")['default']
export const LazyPhotoDetailMap: typeof import("../components/photoDetail/map.vue")['default']
export const LazyPhotoDetailSlider: typeof import("../components/photoDetail/slider.vue")['default']
export const LazyUserAwards: typeof import("../components/user/awards.vue")['default']
export const LazyUserMainInfo: typeof import("../components/user/mainInfo.vue")['default']
export const LazyUserPhotos: typeof import("../components/user/photos.vue")['default']
export const LazyUserPopup: typeof import("../components/user/popup/index.vue")['default']
export const LazyUserPopupText: typeof import("../components/user/popup/text.vue")['default']
export const LazyUserPopupUpload: typeof import("../components/user/popup/upload.vue")['default']
export const LazyUserPopupSecond: typeof import("../components/user/popupSecond.vue")['default']
export const LazyIconArrowLine: typeof import("../assets/icons/arrow-line")['default']
export const LazyIconArrow: typeof import("../assets/icons/arrow")['default']
export const LazyIconAward: typeof import("../assets/icons/award")['default']
export const LazyIconBackArrow: typeof import("../assets/icons/back-arrow")['default']
export const LazyIconBannerArrow: typeof import("../assets/icons/banner-arrow")['default']
export const LazyIconBchp: typeof import("../assets/icons/bchp")['default']
export const LazyIconBearOff: typeof import("../assets/icons/bear-off")['default']
export const LazyIconBearOn: typeof import("../assets/icons/bear-on")['default']
export const LazyIconBusOff: typeof import("../assets/icons/bus-off")['default']
export const LazyIconBusOn: typeof import("../assets/icons/bus-on")['default']
export const LazyIconBus: typeof import("../assets/icons/bus")['default']
export const LazyIconCheckbox: typeof import("../assets/icons/checkbox")['default']
export const LazyIconEye: typeof import("../assets/icons/eye")['default']
export const LazyIconLikeDef: typeof import("../assets/icons/like-def")['default']
export const LazyIconLike: typeof import("../assets/icons/like")['default']
export const LazyIconLogoWhite: typeof import("../assets/icons/logo-white")['default']
export const LazyIconLogo: typeof import("../assets/icons/logo")['default']
export const LazyIconMap: typeof import("../assets/icons/map")['default']
export const LazyIconPlusWhite: typeof import("../assets/icons/plus-white")['default']
export const LazyIconPlus: typeof import("../assets/icons/plus")['default']
export const LazyIconSearch: typeof import("../assets/icons/search")['default']
export const LazyIconStar: typeof import("../assets/icons/star")['default']
export const LazyIconTreeOff: typeof import("../assets/icons/tree-off")['default']
export const LazyIconTreeOn: typeof import("../assets/icons/tree-on")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtIcon: typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
